### PR TITLE
[WIP] Replace usage of to-be-deprecated GtkLayout by GtkDrawingArea

### LINKED ISSUE #343: Use GtkDrawingArea instead of GtkLayout
Right now we use a GtkLayout for both the editing pane and the linecount, which works for now, but GtkLayout has been removed in GTK4. We should switch to using a GtkDrawingArea in a GtkViewport instead.

### PR DESCRIPTION
**Pull request by paulolieuthier**
Fixes #343.

### CODE REVIEW

**Comment by paulolieuthier** [comment]
@Cogitri I need help. This is how it looks after adding many, non-empty, lines:
image

I'm not sure what causes it. Wrapping the drawing area in a viewport seems to make no difference.

**Comment by Cogitri** [comment]
Not quite sure if I see the problem

**Comment by paulolieuthier** [comment]
There's no empty lines in my screenshot. The space you see below the text and below the line numbers is appearing from nowhere.

**Comment by Cogitri** [comment]
Ah, got it. I just took a look and it seems like we're trying to be a bit too smart in `handle_da_draw`:

* We often use `- vadj.get_value()` in that function to calculate the offset from the top of the screen. We don't have to do that anymore when we're using a `GtkViewPort` (and please do use one for the `edit_area` `GtkDrawingArea` at least, I don't think we'll need it for the `line_count`)
* We need to call `self.view_item.edit_area.queue_draw` in `EditView::update_visible_scroll_region` to ensure we're always redrawing the view when we're scrolling since `GtkViewPort` doesn't do that for us anymore.
* I think we might need to revert parts of 4dfd6deacf1132815aac9ccbfc4109cf038db017 to fix the issue you're observing. After Tau started to use a `GtkLayout` it just set its size with `set_size` and then `GtkLayout` would do the scrollbar adjustment for us - this doesn't work when we don't use it anymore.

Do you want to give this a shot (with my help? :) ), or do you want me to provide a patch for it? :)

**Comment by Cogitri** [comment]
FWIW this is how I've done it: https://gist.github.com/154ca4a2b3669113ce6c96571909a7ac

**Pull request closed without merging**
