### PR TITLE
fix weblate link: gxi -> Tau

### PR DESCRIPTION
**Pull request by luukvanderduim**
Fix broken link to weblate and diff shows I removed a stray white space.

### CODE REVIEW

**Comment by Cogitri** [comment]
Oh, thanks, looks like I missed that one :)

**Comment by Cogitri** [comment]
Could you please change the commit message to a semantic though, as otherwise done on the repo? Something like `chore(README): fix Weblate link gxi -> Tau` would be nice

**Comment by luukvanderduim** [comment]
Of course. 
Bear with me as this is my first PR.
As I understand it, an already committed and pushed commit message is changed by locally reverting and re-applying the change and message. While it makes sense not to allow for any further changes in the web interface, it does appear a bit clumsy to have a PR with apply, revert and re-apply in the log.

**Comment by Cogitri** [comment]
No worries, glad to be of help. You can squash commits into one by doing `git rebase -i HEAD~~~` and putting `s` in front of your commits. You can also add changes to your latest commit by doing `git commit --amend`. You'll have to force push for both of these with `git push -f`, so only do this for PRs (where you want a clean history) and not for normal repos (where you want a linear history, so your procedure would've been correct).

**Comment by luukvanderduim** [comment]
This might have done what we wanted or do I resubmit the PR?

**Comment by Cogitri** [comment]
Yup, thank you!

**Pull request merged**
